name: call js file

on:
  push:
    branches:
      - main

jobs:
  call-js-file:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v2
      - run: ls
      - run: npm install
      - run: node upload-s3.js --accessKey=${{ secrets.access_key }} --secretKey=${{ secrets.secret_key }} --region=${{ secrets.region }}
      - run: echo Entered the post_build phase...
      - run: echo Build completed on `date`